export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function HelloLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      {children}
      this is company/employ layout!!!
    </div>
  );
}
